### PR TITLE
Try to make flatpak-wrapper work with file names containing spaces

### PR DESCRIPTION
**Pull request by Alexander-Wilms**

### CODE REVIEW

**Comment by Ainstain438** [comment]
Sorry for the late response but how do I make sure I run this specific instance of TexStudio and not the "original" flatpak? What command should I use to run it?

**Comment by Alexander-Wilms** [comment]
`flatpak run org.texstudio.TeXstudio//test`

**Comment by Ainstain438** [comment]
Alright, so the app runs with the command with console output:
```
Gtk-Message: 18:08:57.725: Failed to load module "xapp-gtk3-module"
Qt: Session management error: None of the authentication protocols specified are supported
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
```
(I tried compiling the document twice)
But same error and texput.log-file contents. Were you able to replicate the error?

**Comment by Alexander-Wilms** [comment]
Hm, then I'll have to try it myself next week.

**Comment by Alexander-Wilms** [comment]
@Ainstain438 Can you update and try again. I think it should work now.

**Comment by Ainstain438** [comment]
So I just tried the Build 94518 and TexStudio itself does not create a popup that says "error" and the messages say that the process was successful (see screenshot) however the process does not produce any file (.pdf, .aux e.tc.) except the texput.log which says the same thing as previous builds.

image

My console output looked like this:
```
/app/bin/texstudio.sh: line 5: cd: /app/texlive/lib/perl5/site_perl/: No such file or directory
Gtk-Message: 11:56:37.975: Failed to load module "xapp-gtk3-module"
Qt: Session management error: None of the authentication protocols specified are supported
QFSFileEngine::open: No file name specified
```

Did you ask ChatGPT if it was sure the solution was correct? :laughing:

**Comment by Alexander-Wilms** [comment]
I've now tested it with `set -x` and think now it should actually work:

```
$ ./flatpak-wrapper xelatex -synctex=1 -interaction=nonstopmode "CV -12".tex
+ ./flatpak-wrapper xelatex -synctex=1 -interaction=nonstopmode 'CV -12.tex'
Using TeX Live from host
command: flatpak-spawn --host xelatex -synctex=1 -interaction=nonstopmode "CV -12.tex"
./flatpak-wrapper: line 38: flatpak-spawn: command not found
```

**Comment by Ainstain438** [comment]
When running the installl script the terminal says:
```
error: Can't load uri https://dl.flathub.org/build-repo/77563/org.texstudio.TeXstudio.flatpakref: Server returned status 404: Not Found
```

And when running `flatpak update` the terminal says:
```
F: Warning: Treating remote fetch error as non-fatal since app/org.texstudio.TeXstudio/x86_64/test is already installed: No such ref 'app/org.texstudio.TeXstudio/x86_64/test' in remote texstudio-origin
Nothing to do.
```

So I am not sure if I have the latest TexStudio test version installed. When trying to compile a document with a space in the name it (as last time) doesn't produce a popup error but it doesn't produce a texput.log file. I believe the reason I saw the texput.log file last time  (build 94518) was due to me not clearing that file before.

**Comment by Alexander-Wilms** [comment]
bot, build

**Comment by Alexander-Wilms** [comment]
No idea how to make this work. Seems like there's no way to avoid losing the quotes

**Comment by Ainstain438** [comment]
Yeah the latest build is back to square 1 with regards to how it works but to be honest it's not that big of a deal for me anyway. It sure feels like the first solution would work (based on my limited experience). Thank your for the attempt anyway!

**Pull request closed without merging**
