### PR TITLE
Use bash script in desktop file

### PR DESCRIPTION
**Pull request by jakobjakobson13**
Fixes https://github.com/flathub/org.texstudio.TeXstudio/issues/110#issuecomment-1279879570

### CODE REVIEW

**Comment by Alexander-Wilms** [comment]
Using desktop-file-edit would be easier:

https://github.com/flathub/org.flightgear.FlightGear/blob/master/org.flightgear.FlightGear.yaml#L165

**Comment by mpanhans** [comment]
Brilliant! I am confirming that this test build resolves the issue in #110 regardless of how TexStudio is launched.

**Comment by jakobjakobson13** [comment]
> Using desktop-file-edit would be easier:
> 
> https://github.com/flathub/org.flightgear.FlightGear/blob/master/org.flightgear.FlightGear.yaml#L165

That is true indeed. I did not know about that Option.

**Comment by Alexander-Wilms** [comment]
Can you force-push a commit using desktop-file-edit?

**Comment by jakobjakobson13** [comment]
@Alexander-Wilms Did I do it how you intented?

**Comment by Alexander-Wilms** [comment]
This would be to be one of the build-commands

**Comment by mpanhans** [comment]
Unfortunately I cannot get this recent test build 3126 to work. For me, it does not find the perl libraries when TexStudio is launched via desktop clicking. It does find the perl libraries when launched with flatpak run command.
The earlier test build 1872 did find the perl libraries no matter how texstudio was launched.

**Comment by Alexander-Wilms** [comment]
Can you try https://github.com/flathub/org.texstudio.TeXstudio/pull/116

**Comment by mpanhans** [comment]
Yes the build in #116 works!

**Comment by jakobjakobson13** [comment]
Superseded by #116 .

**Pull request closed without merging**
