### PR TITLE
Add openjdk11

### PR DESCRIPTION
**Pull request by tilosp**
java is required for bib2gls to work

### CODE REVIEW

**Comment by jakobjakobson13** [comment]
> Build [3422 failed](https://flathub.org/builds/#/builders/32/builds/3422)

The build failed during the validation of the AppData file. I filed a  [bug](https://github.com/texstudio-org/texstudio/issues/608) for this upstream.

**Comment by tilosp** [comment]
bot, build

**Comment by Alexander-Wilms** [comment]
bot, build

**Comment by Alexander-Wilms** [comment]
Thanks a lot

**Pull request merged**
